### ISSUE TITLE
Ball persistence

### ISSUE THREAD

**Issue by zidik** [zidik/soccervision#3]
1) When robot sees one standing ball, it should not create new object but update the object information

**Comment by kolibakter** [comment]
Robot now has a list of persistent balls in vision.cpp, that is updated according to visible balls.

**Comment by kolibakter** [comment]
Nevermind me. Actually I will leave this open, since very fast moving balls have problems with persistency. Might be fixed when code is run without debug GUI (e. g. at 60fps), but I currently don't know how i would test it properly.

**Comment by kolibakter** [comment]
Now works better. Still haven't tested @60fps, but I believe in my code. Will close this issue.
