### ISSUE TITLE
Corner detection

### ISSUE THREAD

**Issue by zidik** [zidik/soccervision#7]
Corners should be detected from vision.
This can be achieved by finding field-lines  (white to black transitions) from vision.
Found transitions are translated to points in real world.
Points are analyzed (how?) to determine if it represents a corner

First implementation can just return the point with the largest distance as a corner. (should be close enough)
The next implementation could use some linear regression.

**Comment by jaantti** [comment]
Basic corner detection is working. That means I check each black-white color transition point. If the distance to the point is increasing and then starts decreasing, that indicates a corner.

Next step would be eliminate noise and implement some checks, to determine the probability of the corner.

**Comment by jaantti** [comment]
Now the code will calculate slopes for points first->corner and corner->last. If -1.2 <= slope1*slope2 <= -0.8 then it is a corner. This should remove the false positives. I have to do more testing to see, if there are some more small improvement I can make.
